credentials:
  usernames:
    mohit:
      email: <Your email id>
      name: <Your Name>
      password: '123' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: "some_signature_key"
  name: "some_cookie_name"
preauthorized:
  emails:
  - <Your email id>