credentials:
  usernames:
    mohit:
      email: mohitmanglani2906@gmail.com
      name: Mohit Manglani
      password: '123' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: "some_signature_key"
  name: "some_cookie_name"
preauthorized:
  emails:
  - mohitmanglani2906@gmail.com